spring:
  profiles:
    active: dev

  application:
    name: eucl

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8000

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs


jwt:
  secretKey: ${JWT_SECRET_KEY}



